inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3.4

Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
